### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nizartaha** [BlockResearchGroup/compas_libigl#10]
I am trying to install compas_libigl on Windows and i got the following error in the last line `pip install -e .` from the instructions written here: https://blockresearchgroup.github.io/compas_libigl/gettingstarted.html

```
(igl) C:\Windows\System32\compas_libigl>pip install -e .
Obtaining file:///C:/Windows/System32/compas_libigl
Installing collected packages: compas-libigl
  Running setup.py develop for compas-libigl
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\igl\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\System32\\compas_libigl\\setup.py'"'"'; __file__='"'"'C:\\Windows\\System32\\compas_libigl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Windows\System32\compas_libigl\
    Complete output (70 lines):
    running develop
    running egg_info
    writing src\compas_libigl.egg-info\PKG-INFO
    writing dependency_links to src\compas_libigl.egg-info\dependency_links.txt
    writing top-level names to src\compas_libigl.egg-info\top_level.txt
    reading manifest file 'src\compas_libigl.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'data'
    no previously-included directories found matching 'temp'
    warning: no files found matching 'LICENSE'
    warning: no previously-included files found matching 'requirements-dev.txt'
    warning: no previously-included files found matching 'pytest.ini'
    warning: no previously-included files found matching '.bumpversion.cfg'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching 'tasks.py'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.nb[ic]' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    writing manifest file 'src\compas_libigl.egg-info\SOURCES.txt'
    running build_ext
    -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
    CMake Error at CMakeLists.txt:2 (project):
      Failed to run MSBuild command:
        C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe
      to get the value of VCTargetsPath:
        Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        MSBUILD : error MSB1009: Project file does not exist.
        Switch: VCTargetsPath.vcxproj
      Exit code: 1
    -- Configuring incomplete, errors occurred!
    See also "C:/Windows/System32/compas_libigl/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Windows\System32\compas_libigl\setup.py", line 124, in <module>
        cmdclass=dict(build_ext=CMakeBuild),
      File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\setuptools\__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\envs\igl\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\envs\igl\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\envs\igl\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\setuptools\command\develop.py", line 38, in run
        self.install_for_development()
      File "C:\ProgramData\Anaconda3\envs\igl\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "C:\ProgramData\Anaconda3\envs\igl\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\envs\igl\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Windows\System32\compas_libigl\setup.py", line 46, in run
        self.build_extension(ext)
      File "C:\Windows\System32\compas_libigl\setup.py", line 79, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "C:\ProgramData\Anaconda3\envs\igl\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Windows\\System32\\compas_libigl', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Windows\\System32\\compas_libigl\\src', '-DPYTHON_EXECUTABLE=C:\\ProgramData\\Anaconda3\\envs\\igl\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Windows\\System32\\compas_libigl\\src', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\igl\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\System32\\compas_libigl\\setup.py'"'"'; __file__='"'"'C:\\Windows\\System32\\compas_libigl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(igl) C:\Windows\System32\compas_libigl>

```

**Comment by brgcode** [comment]
you have the repo in `C:\Windows\System32`. this is your Windows system folder. not sure if this is the main cause of the problem but it will certainly not help.

try cloning the repo (`compas_libigl`) in a non-sytem folder and try running the installation procedure again. if that still doesn't work we can have another look.

for example, clone into your Home folder, or even on your Desktop...

**Comment by nizartaha** [comment]
It worked by cloning it to other folder.
