### ISSUE TITLE
TypeError: cannot unpack non-iterable Mesh object in examples isolines and boundaries

### ISSUE THREAD

**Issue by nizartaha** [BlockResearchGroup/compas_libigl#11]
I tried to run example files isolines and boundaries from Anaconda prompt (Anaconda3) but i got the same error for both . 
on Windows compas version ` 0.16.1`

```
(igl) C:\Users\nizart\Documents\Projects\compas_libigl>python C:\Users\nizart\Downloads\boundaries.py
Traceback (most recent call last):
  File "C:\Users\nizart\Downloads\boundaries.py", line 24, in <module>
    boundaries = igl.trimesh_boundaries(mesh)
  File "c:\users\nizart\documents\projects\compas_libigl\src\compas_libigl\boundaries\__init__.py", line 37, in trimesh_boundaries
    V, F = M
TypeError: cannot unpack non-iterable Mesh object

(igl) C:\Users\nizart\Documents\Projects\compas_libigl>python C:\Users\nizart\Downloads\isolines.py
Traceback (most recent call last):
  File "C:\Users\nizart\Downloads\isolines.py", line 25, in <module>
    vertices, edges = igl.trimesh_isolines(mesh, scalars, 10)
  File "c:\users\nizart\documents\projects\compas_libigl\src\compas_libigl\isolines\__init__.py", line 43, in trimesh_isolines
    V, F = M
TypeError: cannot unpack non-iterable Mesh object

(igl) C:\Users\nizart\Documents\Projects\compas_libigl>
```

**Comment by brgcode** [comment]
yes that is because of a recent update in compas. just convert the mesh to vertices and faces explicitly before using it as input.
```python
boundaries = igl.trimesh_boundaries(mesh.to_vertices_and_faces())
```

**Comment by nizartaha** [comment]
Ok. Thanks

**Comment by nizartaha** [comment]
in Isolines example , is there a way to order the resulted segments of polylines as per `N (int, optional) – The number of isolines.` . or create `N` polylines of the resulted small polyline segments.

**Comment by brgcode** [comment]
could you file this as a separate issue or pull request?
thanks
